"""empty message

Revision ID: 11ebda3b85f7
Revises: cacb7a28e4f
Create Date: 2015-10-26 18:19:29.881000

"""

# revision identifiers, used by Alembic.
revision = '11ebda3b85f7'
down_revision = 'cacb7a28e4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
