"""empty message

Revision ID: 2995b77c1f99
Revises: 43eb0cb21027
Create Date: 2015-10-27 09:04:02.325000

"""

# revision identifiers, used by Alembic.
revision = '2995b77c1f99'
down_revision = '43eb0cb21027'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_time_stamp', 'post', ['time_stamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_time_stamp', 'post')
    op.drop_table('post')
    ### end Alembic commands ###
