"""empty message

Revision ID: 43eb0cb21027
Revises: c728be7f7df
Create Date: 2015-10-26 20:13:56.719000

"""

# revision identifiers, used by Alembic.
revision = '43eb0cb21027'
down_revision = 'c728be7f7df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
