"""empty message

Revision ID: c728be7f7df
Revises: 2f8ffd118244
Create Date: 2015-10-26 18:38:02.390000

"""

# revision identifiers, used by Alembic.
revision = 'c728be7f7df'
down_revision = '2f8ffd118244'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
